server:
  port: 8077
  error:
    include-stacktrace: never

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sba_db;INIT=RUNSCRIPT FROM 'classpath:scheme.sql'\;RUNSCRIPT FROM 'classpath:data.sql';CACHE_SIZE=0
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

assets-service:
  suppression-url: http://localhost:8087/api/v1/suppression-info